README.mkd
Some linux distros have sh symlinked to dash. So I have added a clarification to use bash for the distros.
=> Added clarification to use bash

README.mkd
My rational for this is:
1. Most linux desktop users are using some kind of debian/ubuntu/mint, so why not have them catered for primarily?
2. The bash instructions work for everyone who has bash. Last time I checked, that was 99% of the linux community, I'd say that for those who are able to install zsh, it would be even higher.
=> Simplify installation instructions

install
User can also supply as a first parameter the script to append to zsh-autosuggestions. 
Relates to https://github.com/tarruda/zsh-autosuggestions/issues/50
=> Install script now looks for .zshrc in $ZDOTDIR as well.

autosuggestions.zsh
This (at least partially) fixes #6 and https://github.com/zsh-users/zsh-syntax-highlighting/issues/164. Highlighting now works correctly when completion is accepted using Ctrl+e (end-of-line), but doesn’t work well when I paste some command to terminal from the clipboard.
=> Fix highlight cache invalidation

autosuggestions.zsh
=> Fix highlighting for paths completion using Tab

autosuggestions.zsh
I’ve screwed indentation in `autosuggest-backward-delete-char` function in #57; fixing it now.
=> Fix indentation in autosuggest-backward-delete-char()

README.md, autosuggestions.zsh
It basically means this: go to the end of line (i.e. accept the suggestion) and then hit enter.
I have binded this widget to Cmd + Enter in my terminal and it’s extremely convenient. :smile_cat:
/cc @faceleg
=> Add widget autosuggest-execute-suggestion

README.md
Due to using a forked version of zsh-syntax-highlighting, you also get along the bug that causes a [bell on every keystroke][1], using zsh-users/zsh-syntax-highlighting instead I avoided this bug.
[1]: https://github.com/zsh-users/zsh-syntax-highlighting/issues/200
=> Avoid bell on all keysrtokes

autosuggestions.zsh
Adds `$ZLE_AUTOSUGGEST_ALL_WIDGETS` array which groups `self-insert`, `magic-space`, `backward-delete-char`, and `accept-line` with other widget arrays for easy looping.
Removes all references to `autosuggest-*-orig` widgets in favor of the ['.'-prefixed names](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets) (i.e. `.self-insert` instead of `autosuggest-self-insert-orig`)
Extracts widget setup code to two new functions: `autosuggest-hook-widgets` and `autosuggest-restore-widgets`
Calls `autosuggest-restore-widgets` when sourced to fix issue #84.
Tested locally with zsh 5.0.7 and 5.2.
=> Restore standard widgets to fix segfault when re-sourcing autosuggestions.zsh

README.md, src/bind.zsh, src/config.zsh, src/widgets.zsh, zsh-autosuggestions.zsh
(Originally PR #122, retarget it to features/execute_widget branch.)
Add back autosuggest-execute-suggestion from #61 which is removed after rewriting.
=> Add an autosuggest widget: autosuggest-execute.

Makefile, script/test-strategy-default.zsh, script/test-strategy-match-prev-cmd.zsh, src/strategies/default.zsh, src/strategies/match_prev_cmd.zsh, src/suggestion.zsh, zsh-autosuggestions.zsh
Re-raised #129 as requested. There is also a bugfix for the default strategy. Feedback is welcome.
=> Add match_prev_cmd strategy and fix default strategy

README.md, script/test.zsh, src/bind.zsh, src/config.zsh, src/widgets.zsh, zsh-autosuggestions.zsh
This adds a new widget, `autosuggest-execute`, that accepts and executes the current suggestion.
It is not triggered by any widgets by default. `ZSH_AUTOSUGGEST_EXECUTE_WIDGETS` is empty by default, but widgets can be added to that array after sourcing the plugin or the widget can be used with `bindkey`.
- You can add widgets to `ZSH_AUTOSUGGEST_EXECUTE_WIDGETS`. For example, this will accept and execute the suggestion when the `accept-line` widget is triggered (usually when you press <kbd>enter</kbd>).
```shell
ZSH_AUTOSUGGEST_CLEAR_WIDGETS=("${(@)ZSH_AUTOSUGGEST_CLEAR_WIDGETS:#accept-line}")
ZSH_AUTOSUGGEST_EXECUTE_WIDGETS+=(accept-line)
```
- You can bind a keypress to it using `bindkey`. For example, this will accept and execute the suggestion when you press <kbd>enter</kbd>:
``` …
```
=> Add a widget to accept and execute the current suggestion.

src/widgets.zsh, test/bind_test.zsh, test/widgets/accept_test.zsh, test/widgets/clear_test.zsh, test/widgets/execute_test.zsh, test/widgets/modify_test.zsh, test/widgets/partial_accept_test.zsh, zsh-autosuggestions.zsh
Should fix issue #135, compatibility with `zaw`.
=> Keep track of return value from original widget (#135)

zsh-autosuggestions.plugin.zsh
I have fixed the missing brackets in plugin.zsh file. Now it works flawlessly under msys2 on Windows.
I have closed the other pull request as, being frank, I didn't know how to add a somthing from a different branch to it.
=> Adjust plugin.zsh file to run on zsh 5.1 in mSYS2.

README.md, src/strategies/match_prev_cmd.zsh, zsh-autosuggestions.zsh
This strategy relies on the history being exactly in the order in which
commands have been entered.  Therefore, options like suppressing
duplicates or expiring duplicates first will lead to unexpected
suggestions.
=> Document caveats of match_prev_cmd strategy

README.md, src/config.zsh, src/widgets.zsh, test/widgets/modify_test.zsh, zsh-autosuggestions.zsh
Make buffer max size configurable, defaulted to infinity ($ZSH_BUFFER_MAX_SIZE).
=> Disable autosuggest if buffer is too large

src/config.zsh, zsh-autosuggestions.zsh
This commit adds the 'emacs-forward-word' widget to the list of partial accept widgets.
=> Add 'emacs-forward-word'

README.md
I added instructions for how to install `zsh-autosuggestions` via the AUR (for Arch Linux) and Homebrew (for macOS).
=> Added installation instructions for AUR, Homebrew

.rubocop.yml
YAML does not permit tabs and many parsers will error when loading a tab-indented file - http://www.yaml.org/faq.html
=> replace tabs in Rubocop config with spaces

src/strategies/match_prev_cmd.zsh, zsh-autosuggestions.zsh
this should fix issues #247 and #258 where pattern-matching characters in the buffer are not escaped before matching against history when using the match_prev_cmd strategy.
=> escape pattern-matching chars on $prefix for match_prev_cmd strategy

src/bind.zsh, zsh-autosuggestions.zsh
Fixes #228
Quoting my comment on the ticket:
>This happens because `_zsh_autosuggest_invoke_original_widget()` returns `1` when provided no 'original widget' (which it won't be in this case), and the `_zsh_autosuggest_widget_*()` functions pass this status on. Per the ZLE widget documentation:
>
>>A non-zero return status causes the shell to beep when the widget exits, unless the BEEP options was unset or the widget was called via the zle command.
>
>I'm not super familiar with the code base yet but i don't see any reason why `_zsh_autosuggest_invoke_original_widget()` needs to return `1` here — it's not an error condition and it doesn't seem to provide any other useful information to the caller. I've only tested briefly but i haven't seen any issues so far with just having it always …
=> Avoid ringing bell when accepting suggestions

spec/integrations/async_line_or_beginning_spec.rb, src/config.zsh, zsh-autosuggestions.zsh
Should fix #241 and #227.
These widgets rely on `$LASTWIDGET` being set to restore the cursor position. When asynchronous suggestions are enabled, and the widget triggers a suggestion to be fetched, `autosuggest-suggest` will be called and $LASTWIDGET will be set to it.
=> Don't fetch suggestions after [up,down]-line-or-beginning-search

README.md
Handle installation for oh my zsh without ZSH_CUSTOM defined the same way it is done in [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md#oh-my-zsh).
=> make Oh my zsh install works without ZSH_CUSTOM defined

src/strategies/completion.zsh, zsh-autosuggestions.zsh
Just insert the first completion directly into the buffer and read the whole buffer from the zpty.
Should fix a couple issues reported in #342.
=> Improve completion suggestions

src/config.zsh, src/widgets.zsh, zsh-autosuggestions.zsh
I decided to turn on `warn_create_global` recently, but a lot of my `zshrc` stuff happens inside functions to prevent leaking temp variables, and zsh-autosuggestions doesn't like that:
```
% zsh --warn-create-global -fc '() { source ./zsh-autosuggestions.zsh }'
./zsh-autosuggestions.zsh:45: scalar parameter ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE created globally in function (anon)
./zsh-autosuggestions.zsh:48: scalar parameter ZSH_AUTOSUGGEST_ORIGINAL_WIDGET_PREFIX created globally in function (anon)
./zsh-autosuggestions.zsh:52: array parameter ZSH_AUTOSUGGEST_STRATEGY created globally in function (anon)
./zsh-autosuggestions.zsh:55: array parameter ZSH_AUTOSUGGEST_CLEAR_WIDGETS created globally in function (anon)
./zsh-autosuggestions.zsh:70: array parameter ZSH_AUTOSUGGEST_ACCEPT_WIDGETS …
```
=> Set global parameters with typeset -g

src/widgets.zsh, zsh-autosuggestions.zsh
Some people have gotten used to setting ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE to an empty string rather than leaving it unset. This lets them continue to do that without getting any warnings (e.g. "bad math expression: operand expected at end of string").
=> Allow setting max size to empty string (GitHub #422)

spec/async_spec.rb, src/config.zsh, zsh-autosuggestions.zsh
Supercedes #438. Thanks @henrebotha!
Like `{up,down}-line-or-beginning-search`, this widget relies on `$LASTWIDGET` being set to function correctly on subsequent invocations.
When asynchronous suggestions are enabled, and the widget triggers a suggestion to be fetched, `autosuggest-suggest` will be called and `$LASTWIDGET` will be set to it.
=> Don't fetch suggestions after copy-earlier-word

spec/line_init_spec.rb, src/bind.zsh, src/config.zsh, zsh-autosuggestions.zsh
Use case suggested by @romkatv uses zle-line-init to restore buffer after running a widget to cd up one level (GitHub #431).
As far as I can tell, the ignoring of zle-line-* was added in commit 9788c2e to support some deprecation warnings that were removed some time ago.
The pattern was then widened in commit 0c940e7 to zle-* to fix problems encountered when wrapping zle-isearch-update.
This commit removes the hard coded ignore of all zle-* widgets and puts zle-isearch-update and zle-keymap-select into the default list of widgets to be ignored. It leaves zle-line-init and zle-line-finish not ignored so that suggestions will be fetched after they are run.
=> Wrap zle-line-init to support fetching suggestions on line init

src/async.zsh, zsh-autosuggestions.zsh
When using async mode, stale background processes will not be cancelled when a new one starts. This shouldn't cause any real issues since the processes should eventually finish and be cleaned up anyway, and removing the handler with `zle -F` means that stale suggestions should never be shown.
Closes #441.
=> Degrade gracefully on systems missing zsh/system module

README.md
In reply to https://github.com/zsh-users/zsh-autosuggestions/issues/416#issuecomment-503621106, this PR contains the following changes to README.md:
* Added a note for iTerm2 users under readme/configuration/highlight style.
* Changed the link to the issue list under troubleshooting so that the default filters (only open issues) are not applied.
=> Possible fix for #416

spec/integrations/vi_mode_spec.rb, src/widgets.zsh, zsh-autosuggestions.zsh
Typing `d` and then `l` runs `vi-delete` and then `vi-forward-char`.  However, by default, `vi-forward-char` is configured to accept the suggestion. So in that case, the suggestion was being accepted and the cursor set to the end of the buffer before the deletion was run.
The reason the user doesn't see the suggestion accepted is that `vi-delete` doesn't finish until the movement widget is run, so we're already inside of a `modify` when `accept` is called. `modify` unsets `POSTDISPLAY` before calling the original widget so when we get to the accept function, `POSTDISPLAY` is empty and thus accepting the suggestion is a no-op.
The fix is to make sure we reset the cursor to the correct place before running the original widget.
We skip the test for versions of zsh below 5.0.8 since there was …
=> Fix deleting last character in vi mode (#302)

spec/options/widget_lists_spec.rb, src/widgets.zsh, zsh-autosuggestions.zsh
`$max_cursor_pos` in this case was not the correct value to use. It was calculated based on the old length of the `$BUFFER`. After the suggestion is accepted, we need to recalculate the new max cursor length and use it to set the `$CURSOR`.
Fixes issue #452. Follow-up to issue #302 (PR #450).
=> Fix moving cursor to end of buffer when suggestion accepted

README.md, spec/strategies/history_spec.rb, spec/strategies/match_prev_cmd_spec.rb, src/strategies/history.zsh, src/strategies/match_prev_cmd.zsh, zsh-autosuggestions.zsh
Set `ZSH_AUTOSUGGEST_HISTORY_IGNORE` to a glob pattern to have the `history` and `match_prev_cmd` suggestion strategies never make suggestions matching that pattern.
For example, set to `"cd *"` to never suggest any `cd` commands from history (see issues #340 and #425). Or set to `"?(#c50,)"` to never suggest anything 50 characters or longer (see issue #429).
TODO
=> Allow configuring to ignore history entries matching a pattern

INSTALL.md
Hey @nicoulaj, I'm finally getting to issue #222. I just copied what you had for zsh-completions and `s/completions/autosuggestions/g`.
Got 404's (or equivalent) for Gentoo, Slackware, and MacPorts so went ahead and removed those.
Would appreciate if you could review when/if you have time. Thanks!
=> Add package links to install docs (#222)

.circleci/config.yml
We are getting errors on circle ci builds (e.g. see https://circleci.com/gh/zsh-users/zsh-autosuggestions/381):
> CircleCI was unable to run the job runner because we were unable to execute commands in build container.
> 
> This typically means that the build container entrypoint or command is terminating the container prematurely, or interfering with executed commands.  Consider clearing entrypoint/command values and try again.
Folks in [this thread](https://discuss.circleci.com/t/circleci-was-unable-to-run-the-job-runner/31894/18) suggest removing the `command: /sbin/init` line initially [added by the v1 => v2 migration script](https://github.com/zsh-users/zsh-autosuggestions/commit/affe7c687e329f881ae92e95670979b0f728e613#diff-1d37e48f9ceff6d8030570cd36286a61R32).
=> Fix circle ci build issues

src/strategies/completion.zsh, zsh-autosuggestions.zsh
Follow-up to technique tried in commit d94475c after I learned about the `@` flag to keep empty strings in the array.
=> cleanup: Split on null bytes instead of pattern matching

src/widgets.zsh, zsh-autosuggestions.zsh
The check on length of `$POSTDISPLAY` is in support of the test for `vi-delete` on the last char of the buffer with `dl`.
Fixes issue #482.
I think this also supersedes PR #294.
=> Call original widget before moving cursor when accepting suggestion

README.md, spec/strategies/completion_spec.rb, src/strategies/completion.zsh, zsh-autosuggestions.zsh
Set ZSH_AUTOSUGGEST_COMPLETION_IGNORE to a glob pattern to have the completion suggestion strategy never make suggestions when the buffer matches the pattern.
This can be helpful when some completion routines you have are particularly expensive and you want to prevent them from running automatically on every keystroke.
See GitHub issue #463.
=> Allow skipping completion suggestions when buffer matches a pattern

src/bind.zsh, src/widgets.zsh, zsh-autosuggestions.zsh
To avoid wrapping the built-in widgets (e.g. `autosuggest-fetch`, `autosuggest-toggle`), we were ignoring all widgets whose names start with `autosuggest-`. This had the downside of preventing wrapping of user-defined widgets whose names happened to also start with that prefix.
By being more specific about the exact built-in widgets we want to avoid wrapping, we can allow users to define widgets whose names start with `autosuggest-`.
See #496.
=> Be more specific about the built-in widgets we want to avoid wrapping

src/widgets.zsh, zsh-autosuggestions.zsh
We are already using this method in other places.
For example: `ZSH_AUTOSUGGEST_USE_ASYNC`
=> cleanup: Use more idiomatic method of checking if var is set

README.md, spec/options/use_async_spec.rb, src/start.zsh, src/strategies/completion.zsh, zsh-autosuggestions.zsh
Allow users to override the default by unsetting (or setting) the `ZSH_AUTOSUGGEST_USE_ASYNC` variable.
See GitHub issue #498.
=> Enable async mode by default in newer versions of zsh

src/async.zsh, zsh-autosuggestions.zsh
The bug is fixed in recent version of zsh, so the workaround is not needed anymore for fresh zsh:
https://github.com/zsh-users/zsh-autosuggestions/issues/364
=> Disable ^C async workaround for zsh version 5.8 and later

src/widgets.zsh, zsh-autosuggestions.zsh
1. Run `zsh -f`.
2. Run this:
```zsh
function bye() { BUFFER=bye }
zle -N bye
bindkey '^B' bye
print -s 'hibye unexpected'
source ~/zsh-autosuggestions/zsh-autosuggestions.zsh
```
3. Type `hi` and press <kbd>Ctrl-B</kbd>.
Expected: `POSTBUFFER` is empty.
Actual: `POSTBUFFER` is " unexpected".
=> Fix a bug in partial acceptance of suggestions

INSTALL.md
See https://github.com/Homebrew/homebrew-core/commit/442f9cc511ce6dfe75b96b2c83749d90dde914d2
Also, it might be nice to include `brew install zsh-autosuggestions` there as the package definition doesn't help someone with how to actually _install_ it unless they know how homebrew works. Also, if you aren't aware of homebrew's `Caveats`, it might be easy to miss
```
==> Caveats
To activate the autosuggestions, add the following at the end of your .zshrc:
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
You will also need to restart your terminal for this change to take effect.
```
So I would also suggest adding that to your install documentation page.
=> Update INSTALL link for Mac OS - homebrew moved under z/

.gitignore
Created a .gitignore file that ignores the zsh word code (*.zwc) compiled with the zcompile command for zsh scripts.
=> Create .gitignore for *.zwc

src/async.zsh, zsh-autosuggestions.zsh
I have a wrapper shell function for `exec()`  in my environment which started to behave unexpectedly after I updated `zsh-autosuggestions`.  I'm using the `unset ZSH_AUTOSUGGEST_USE_ASYNC` suggestion from the README as a workaround for now, but it'd be nice to enable async. This PR added the `builtin` precommand modifier to all occurances to `exec` in the code to ensure we use the builtin `exec` command _"rather than a shell function or external command"_.
=> Ensure that we're using the builtin exec

src/async.zsh, zsh-autosuggestions.zsh
This prevents the request cancelling logic from closing an unrelated fd that happens to reuse the same number.
https://github.com/zsh-users/zsh-autosuggestions/blob/a411ef3e0992d4839f0732ebeb9823024afaaaa8/src/async.zsh#L12-L15
=> Always reset file descriptor after consuming it

INSTALL.md
Adds a link to the `zsh-autosuggestions` package in FreeBSD Ports.
=> INSTALL.md: Add FreeBSD
